services:
  devicemanagement.api:
    image: devicemanagement.api
    build:
      context: .
      dockerfile: src/DeviceManagement.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DeviceManagementDB;User Id=sa;Password=DeviceManagement123!;TrustServerCertificate=true;
      - Jwt__SecretKey=DeviceManagement-SuperSecretKey-2024-MinimumLength32Characters!
      - Jwt__Issuer=DeviceManagement.API
      - Jwt__Audience=DeviceManagement.Client
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - device-network
    restart: unless-stopped

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-devicemanagement
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DeviceManagement123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./scripts:/scripts
    networks:
      - device-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P DeviceManagement123! -C -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  sqlserver_data:

networks:
  device-network:
    driver: bridge